// ── Enums / Unions ──────────────────────────────────────────────

export type TaskCategory = 'kuliah' | 'project' | 'klien' | 'joki' | 'pribadi' | 'lainnya'

export type TaskStatus =
  | 'belum_dimulai'
  | 'sedang_dikerjakan'
  | 'menunggu'
  | 'revisi'
  | 'selesai'
  | 'dibatalkan'

export type TaskPriority = 'critical' | 'high' | 'medium' | 'low'

// ── Category-specific detail blocks ─────────────────────────────
// Only the block matching `task.category` is expected to be populated.

export interface KuliahDetails {
  mataKuliah: string
  dosen?: string
  pertemuan?: string
}

export interface JokiDetails {
  namaClient: string
  kontakClient?: string
  harga: number
  dp: number
  // sisaPembayaran is derived (harga - dp), not stored
}

export interface KlienDetails {
  namaClient: string
  namaProject: string
  nilaiProject: number
  linkProject?: string
}

// ── Core Task entity ─────────────────────────────────────────────

export interface Task {
  id: string
  title: string
  description: string
  category: TaskCategory
  deadline: string | null // ISO datetime string, null = no deadline
  status: TaskStatus
  priority: TaskPriority
  progress: number // 0–100
  notes: string
  createdAt: string // ISO datetime
  completedAt: string | null // ISO datetime, set when status -> 'selesai'
  archived: boolean

  kuliahDetails?: KuliahDetails
  jokiDetails?: JokiDetails
  klienDetails?: KlienDetails
}

// ── Input shapes ──────────────────────────────────────────────────
// title + category are mandatory; everything else has sane defaults
// generated by the service layer (id, createdAt, completedAt, archived).

export type CreateTaskInput = Pick<Task, 'title' | 'category'> &
  Partial<
    Pick<
      Task,
      | 'description'
      | 'deadline'
      | 'status'
      | 'priority'
      | 'progress'
      | 'notes'
      | 'kuliahDetails'
      | 'jokiDetails'
      | 'klienDetails'
    >
  >

export type UpdateTaskInput = Partial<Omit<Task, 'id' | 'createdAt'>> & {
  id: string
}

// ── Labels & UI metadata ──────────────────────────────────────────

export const TASK_CATEGORY_LABELS: Record<TaskCategory, string> = {
  kuliah: 'Kuliah',
  project: 'Project',
  klien: 'Klien',
  joki: 'Joki',
  pribadi: 'Pribadi',
  lainnya: 'Lainnya',
}

export const TASK_STATUS_LABELS: Record<TaskStatus, string> = {
  belum_dimulai: 'Belum Dimulai',
  sedang_dikerjakan: 'Sedang Dikerjakan',
  menunggu: 'Menunggu',
  revisi: 'Revisi',
  selesai: 'Selesai',
  dibatalkan: 'Dibatalkan',
}

export const TASK_PRIORITY_LABELS: Record<TaskPriority, string> = {
  critical: 'Critical',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
}

export const TASK_CATEGORIES: TaskCategory[] = [
  'kuliah',
  'project',
  'klien',
  'joki',
  'pribadi',
  'lainnya',
]

export const TASK_STATUSES: TaskStatus[] = [
  'belum_dimulai',
  'sedang_dikerjakan',
  'menunggu',
  'revisi',
  'selesai',
  'dibatalkan',
]

export const TASK_PRIORITIES: TaskPriority[] = ['critical', 'high', 'medium', 'low']

// ── Derived / helper types used by the UI ──────────────────────────

export type DeadlineUrgency = 'overdue' | 'today' | 'soon' | 'normal' | 'none'

export interface TaskSummary {
  total: number
  completed: number
  incomplete: number
  dueToday: number
  overdue: number
}

export interface TaskFilters {
  search: string
  category: TaskCategory | 'all'
  status: TaskStatus | 'all'
  priority: TaskPriority | 'all'
  sortBy: 'deadline_asc' | 'deadline_desc' | 'priority' | 'created_desc'
  showArchived: boolean
}
